on:
  pull_request:
  push:
    branches:
      - main # Replace with your default branch if different
name: Test
jobs:
  lint:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: fmt
        run: test -z $(gofmt -l .)

      - name: vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: staticcheck
        run: $(go env GOPATH)/bin/staticcheck ./...

  test:
    runs-on: macos-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Test
        run: go test -race ./... 